# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-03 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='\u6d88\u606f')),
                ('addtime', models.DateTimeField(auto_now=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yonghu.Category', verbose_name='\u6765\u6e90')),
            ],
            options={
                'verbose_name': '\u6d88\u606f',
                'verbose_name_plural': '\u6d88\u606f',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=100, verbose_name='\u5bc6\u7801')),
                ('realname', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('face', models.ImageField(blank=True, default='', upload_to='face/%Y/%m/%d', verbose_name='\u5934\u50cf')),
                ('url', models.CharField(blank=True, default='', max_length=200, verbose_name='\u4e2a\u4eba\u4e3b\u9875')),
                ('about', models.TextField(blank=True, default='', max_length=1000, verbose_name='\u5173\u4e8e\u6211')),
                ('addtime', models.DateTimeField(auto_now=True, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('friend', models.ManyToManyField(related_name='_userprofile_friend_+', to='yonghu.UserProfile', verbose_name='\u670b\u53cb')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yonghu.UserProfile', verbose_name='\u53d1\u5e03\u8005'),
        ),
    ]
