# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-07 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0003_auto_20180503_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='realname',
        ),
    ]
