# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-08 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0005_auto_20180507_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='\u7535\u8bdd'),
        ),
    ]
