# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-08 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0006_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('m', '\u7537'), ('f', '\u5973')], max_length=5, null=True, verbose_name='\u6027\u522b'),
        ),
    ]
