# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-07 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0007_auto_20180508_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userip',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='\u767b\u5f55IP'),
        ),
    ]
