# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-07 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0009_auto_20180707_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='sex',
            new_name='gender',
        ),
    ]
