# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-09 13:53
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0010_auto_20180707_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='message',
            field=tinymce.models.HTMLField(verbose_name='\u6d88\u606f'),
        ),
    ]
