# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 14:58
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0011_auto_20180709_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=20, verbose_name='\u4e8b\u4ef6\u540d')),
                ('e_address', models.CharField(max_length=50, verbose_name='\u4e8b\u4ef6\u5730\u5740')),
                ('e_balance', models.CharField(max_length=20, verbose_name='\u4f59\u989d')),
                ('attr', models.CharField(blank=True, choices=[('col', '\u56fd\u5185\u5927\u5b66'), ('for', '\u56fd\u5916\u5927\u5b66'), ('gam', '\u6e38\u620f'), ('sta', '\u660e\u661f'), ('sto', '\u80a1\u7968'), ('boo', '\u8bfb\u4e66'), ('spo', '\u4f53\u80b2'), ('car', '\u8f66'), ('mus', '\u97f3\u4e50'), ('mov', '\u7535\u5f71')], max_length=20, null=True, verbose_name='\u4e8b\u4ef6\u5c5e\u6027')),
            ],
            options={
                'verbose_name': '\u4e8b\u4ef6\u4fe1\u606f',
                'verbose_name_plural': '\u4e8b\u4ef6\u4fe1\u606f',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='associate',
            field=models.ManyToManyField(blank=True, max_length=50, to='yonghu.Event', verbose_name='\u5173\u8054\u4e8b\u4ef6'),
        ),
    ]
